//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoric
    {
        public int Id { get; set; }
        public int Id_senzor { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<double> MaxTemperatura { get; set; }
        public Nullable<double> MinTemperatura { get; set; }
        public Nullable<double> MedieTemperatura { get; set; }
        public Nullable<double> MaxUmiditate { get; set; }
        public Nullable<double> MinUmiditate { get; set; }
        public Nullable<double> MedieUmiditate { get; set; }
    
        public virtual Senzori Senzori { get; set; }
    }
}
