//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
  
    public partial class Value
    {
        public int Id { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public Nullable<double> Umiditate { get; set; }
        public System.DateTime Timestemp { get; set; }
        public int Id_value { get; set; }
        public string Pompa { get; set; }
    
        public virtual Senzori Senzori { get; set; }
    }
}
